services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: paynora
      POSTGRES_PASSWORD: paynora
      POSTGRES_DB: paynora
    ports:
      - "5432:5432"
    volumes:
      - paynora_postgres_data:/var/lib/postgresql/data

volumes:
  paynora_postgres_data:
